In [3]:
import numpy as np 

In [4]:
np.random.randint(10,30,size=(3,3))

array([[19, 25, 15],
       [15, 16, 27],
       [11, 13, 17]], dtype=int32)

In [5]:
x = np.array([[7,2,3],
              [2,5,2],
              [3,5,1]])

y = np.array([[1,8,3],
              [3,7,2],
              [2,5,3]])

print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [6]:
print(x+y)
print(x-y)
print(x*y)

[[ 8 10  6]
 [ 5 12  4]
 [ 5 10  4]]
[[ 6 -6  0]
 [-1 -2  0]
 [ 1  0 -2]]
[[ 7 16  9]
 [ 6 35  4]
 [ 6 25  3]]


In [7]:
print(x@y) #matrix multiplication

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [8]:
np.dot(x,y)

array([[19, 85, 34],
       [21, 61, 22],
       [20, 64, 22]])

In [9]:
x.prod() #matrix multiplication

np.int64(12600)

In [10]:
round(x.mean())

3

In [11]:
x.mean(axis=0)#mean of each row

array([4., 4., 2.])

In [12]:
y.mean(axis=1)#mean of each row

array([4.        , 4.        , 3.33333333])

In [13]:
print(x.sum())
print(x.var())
print(x.std())

30
3.3333333333333335
1.8257418583505538


In [15]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,50))
print(np.percentile(a,75))

5.0
7.0


In [16]:
b = np.random.randint(11,100,(4,4))
print(b)

[[92 23 15 17]
 [50 67 80 87]
 [31 49 24 69]
 [36 81 85 82]]


In [18]:
print('2x8')
print(b.reshape(2,8))

2x8
[[92 23 15 17 50 67 80 87]
 [31 49 24 69 36 81 85 82]]


In [19]:
print('8x2')
print(b.reshape(8,2))

8x2
[[92 23]
 [15 17]
 [50 67]
 [80 87]
 [31 49]
 [24 69]
 [36 81]
 [85 82]]


In [20]:
print(b.reshape(4,4))

[[92 23 15 17]
 [50 67 80 87]
 [31 49 24 69]
 [36 81 85 82]]


In [21]:
print(b[0])
print(b[0,2])
print(b[-1])
print(b[1:3])
print(b[3:])

[92 23 15 17]
15
[36 81 85 82]
[[50 67 80 87]
 [31 49 24 69]]
[[36 81 85 82]]
